### ISSUE TITLE
How to restrict the slider from continuing after one rotation.

### ISSUE THREAD

**Issue by abbjetmus** [soundar24/vue-round-slider#12]
How to restrict the slider from continuing after one rotation? Want it to stop at the end of the rotation.

**Comment by soundar24** [comment]
@abbjetmus are you expect the below behaviour?

### https://codesandbox.io/s/vue-round-slider-prevent-handle-full-rotation-0l6yo9?file=/src/components/SliderDemo.vue

**Comment by abbjetmus** [comment]
@soundar24 Yes exactly, thank you and for creating the slider. It would be nice to port to Vue3 but a previous comment had a workaround for that.
