### ISSUE TITLE
svgMode

### ISSUE THREAD

**Issue by shalamos** [soundar24/vue-round-slider#3]
Hey Soundar, 

thanks for this useful Vue component. 

Since vue-round-slider is a wrapper for RoundSlider, is it possible to integrate svgMode in vue-round-slider? 

Amos

**Comment by soundar24** [comment]
Hi @shalamos, by default vue-round-slider uses the **svgMode** only, so you don't need to enable manually.. You can just confirm that by inspect the elements..

> however in roundSlider also, from the next major version onwards svgMode will the default mode... and the classic mode rendering will be deprecated...

I am just preparing more demos with code snippets.. here I have the editable demo, which might helps to quick start..
https://codesandbox.io/s/vue-round-slider-demo-oz8el

Thanks...

**Comment by shalamos** [comment]
Thanks, that is great!
